FROM python:3.8.10-alpine
WORKDIR /app

COPY ./requirements.txt ./main.py  ./.flaskenv ./env.py ./
COPY ./api_public ./api_public
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 6000

ENTRYPOINT [ "flask" ]
CMD ["run", "--host=0.0.0.0", "--port=6000"]