FROM python:3.8.10-alpine
WORKDIR /app

COPY ./requirements.txt ./main.py  ./.flaskenv ./env.py ./DB_calls ./DB_tools ./
COPY ./api_public ./api_public
RUN pip install -r ./requirements.txt
RUN apt-get update && apt-get install python3-dev libpq-dev
ENV FLASK_ENV production

EXPOSE 6000

ENTRYPOINT [ "flask" ]
CMD ["run", "--host=0.0.0.0", "--port=6000"]